<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://cdn.tailwindcss.com"></script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add User</title>
</head>
<body>    
    <?php require_once 'adminNav.php'?>

    <div class="sm:m-5 p-6 bg-white p-8 rounded-lg shadow-md">
        <h2 class="text-2xl font-semibold text-center mb-2">Add User</h2>
        <select name="userCourse" id="userCourse" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
            <option value="" selected disable>Select Course</option>
            <option value="BSIT">BSIT</option>
            <option value="BSHM">BSHM</option>
            <option value="BSED">BSED</option>
            <option value="BEED">BEED</option>
        </select>
        <div class="grid grid-cols-2 mb-4 gap-4">
            <div>
                <label for="sid" class="block text-sm font-medium text-gray-700">Student ID</label>
                <input disabled value=<?php
                if(isset($_POST['stud_id'])){
                    $stud_id = htmlspecialchars(strip_tags($_POST['stud_id']));
                }
                else{
                    if (substr($_SESSION['lastsid'], 0, 4) == date("Y")) {
                        $stud_id=((int)$_SESSION['lastsid']+1);
                    } else {
                        $stud_id= (int)(date("Y") . "0001");
                    }                
                }
                
                echo $stud_id;

                ?> type="text" id="sid" name="sid" placeholder="Auto generated by system" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" maxlength="8">
            </div>
            <div>
                <label for="userRole" class="block text-sm font-medium text-gray-700">User Role</label>
                <select name="userRole" id="userRole" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                    <option value="0" selected>Student</option>
                    <option value="1">Admin</option>
                </select>
            </div>            
        </div>
        <div class="flex flex-wrap sm:grap-4 gap-2 mb-4">
            <div class="w-full sm:flex-1">
                <div>
                <label for="password" class="text-sm font-medium text-gray-700">Password</label>
                </div>
                <input type="password" id="password" name="password" placeholder="••••••••" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
            </div>
            <div class="w-full sm:flex-1">
                <div>
                <label for="passwordC" class="text-sm font-medium text-gray-700">Confirm Password</label>
                </div>
                <input type="password" id="passwordC" name="passwordC" placeholder="••••••••" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
            </div>
        </div>
        <div class="flex flex-wrap sm:grap-4 gap-2 mb-4">
            <div class="w-full sm:flex-1">
                <label for="fname" class="text-sm font-medium text-gray-700">First Name</label>
                <input type="text" id="fname" name="fname" placeholder="Enter first name" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" autocapitalize="true">
            </div>
            <div class="w-full sm:flex-1">
                <label for="mname" class="text-sm font-medium text-gray-700">Middle Name</label>
                <input type="text" id="mname" name="mname" placeholder="Enter middle name" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" autocapitalize="true">
            </div>
            <div class="w-full sm:flex-1">
                <label for="lname" class="text-sm font-medium text-gray-700">Last Name</label>
                <input type="text" id="lname" name="lname" placeholder="Enter last name" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" autocapitalize="true">
            </div>
        </div>

        <div class="mb-4">
            <label for="DOB" class="block text-sm font-medium text-gray-700">Date of Birth</label>
            <input type="date" id="DOB" name="DOB" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
        </div>

        <div class="mb-4">
            <label for="address" class="block text-sm font-medium text-gray-700">Address</label>
            <input type="text" id="address" name="address" placeholder="Enter address" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" maxlength="256">
        </div>

        <div class="mb-10">
            <label for="pnumber" class="block text-sm font-medium text-gray-700">Phone Number</label>
            <input type="text" id="pnumber" name="pnumber" placeholder="Enter phone number" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" maxlength="11">
        </div>

        <h2 class="text-2xl font-semibold text-center mb-2">User Guardian Info</h2>
        <div class="flex flex-wrap sm:grap-4 gap-2">
            <div class="w-full sm:flex-1">
                <label for="gfname" class="text-sm font-medium text-gray-700">First Name</label>
                <input type="text" id="gfname" name="gfname" placeholder="Enter first name" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" autocapitalize="true">
            </div>
            <div class="w-full sm:flex-1"> 
                <label for="gmname" class="text-sm font-medium text-gray-700">Middle Name</label>
                <input type="text" id="gmname" name="gmname" placeholder="Enter middle name" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" autocapitalize="true">
            </div>
            <div class="w-full sm:flex-1">
                <label for="glname" class="text-sm font-medium text-gray-700">Last Name</label>
                <input type="text" id="glname" name="glname" placeholder="Enter last name" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" autocapitalize="true">
            </div>
        </div>

        <div class="mb-4">
            <label for="gaddress" class="block text-sm font-medium text-gray-700">Address</label>
            <input type="text" id="gaddress" name="gaddress" placeholder="Enter address" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" maxlength="256">
        </div>

        <div class="mb-10">
            <label for="gpnumber" class="block text-sm font-medium text-gray-700">Phone Number</label>
            <input type="text" id="gpnumber" name="gpnumber" placeholder="Enter phone number" class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" maxlength="11">
        </div>
        <div class="mb-5">
            <label id="passError" class="text-red-500 text-xs hidden">Password doesn't match</label>
            <label id="fieldError" class="text-red-500 text-xs hidden">Fill all necessary fields</label>
        </div>
        
        <input type="button" value="REGISTER" onclick="addUser()" class="w-full bg-indigo-600 text-white py-2 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2">
    </div>
</body>
<script>
    const numsOnlyIds = ["sid", "pnumber", "gpnumber"];

numsOnlyIds.forEach((id) => {
    document.getElementById(id).addEventListener("keypress", function (e) {
        if (e.key < '0' || e.key > '9') {
            e.preventDefault();
        }
    });
});

const AlphaOnlyIds = ["fname", "mname", "lname","gfname", "gmname", "glname"];

AlphaOnlyIds.forEach((id) => {
    document.getElementById(id).addEventListener("keypress", function (e) {
        if (!/[a-zA-Z ]/.test(e.key)) {
            e.preventDefault();
        }
    });
});

        
        let today = new Date();

        
        today.setFullYear(today.getFullYear() - 17);

        
        let dd = String(today.getDate()).padStart(2, '0');
        let mm = String(today.getMonth() + 1).padStart(2, '0');
        let yyyy = today.getFullYear();

        let formattedDate = yyyy + '-' + mm + '-' + dd;

        
        document.getElementById("DOB").value = formattedDate;

</script>
<?php 
    require_once './public/views/dependency.php';
?>
</html>